### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#10]
Remove useless code (I know I have a console.log in there somewhere LMAO)

**Comment by ra100** [comment]
maybe adding `eslint` would help :)

**Comment by EricTurf** [comment]
For sure, feel free to do that if you are interested

**Comment by ra100** [comment]
so let's see how many things will linter change

**Comment by ManuelJF** [comment]
i want to push my branch with the clean up but i don't have permissions :( @EricTurf

**Comment by EricTurf** [comment]
@ManuelJF 

Hi, you have to create a fork of this repo and then push your code to your own fork and then open a PR for it.
