### ISSUE TITLE
[Feature] Add a application shell

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#20]
Currently the page is literally the sudoku game in the center of a white page.

Feel free to add cool stuff around the sudoku game.

Use your imagination, only criteria is that the game is still dead center and easy to see the buttons.

**Comment by bencoullie** [comment]
I'll take a stab at this :) I'll try keep it clean and minimal.

**Comment by EricTurf** [comment]
@bencoullie Feel free to also go all out if you want haha
