### ISSUE TITLE
[Feature] Add home/splash screen

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#38]
Create a splash screen where the person should input a username and then it will allow them to click a play button that will bring them to the game.

The name that they input should be stored in `localStorage` so that we can use that to add them to the leaderboard

**Comment by rasfa98** [comment]
Can I try to implement this?

**Comment by EricTurf** [comment]
@shubhamguptaji You bet

**Comment by kartikpandey2** [comment]
@EricTurf splash screen should ask the user for entering username every time when the difficulty of the game is changed .?

**Comment by EricTurf** [comment]
@kartikpandey2 
Ive been thinking about it and maybe not a username, just the difficulty seems reasonable

**Comment by kartikpandey2** [comment]
@EricTurf I think splash screen should have username and difficulty level should be rendered if localStorage don't have username or if user want to change difficulty level. LocalStorage will be cleared if user close browser.

**Comment by EricTurf** [comment]
@kartikpandey2 Fair enough, do what you please and I will just check out the code thanksd
