### ISSUE TITLE
Please move all styled components 

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#43]
Currently all styled components are in the main component file. Please move them to their own file with the following name `*.styled.js` and reimport the new styled Components

**Comment by bagshik** [comment]
Hey man, I can give this a try 👌

**Comment by bagshik** [comment]
Hmm, I'm not sure which file you mean by 'main component file' because there are a couple of them with styled components in it. Which particular files do I need to refactor? 🤔

**Comment by EricTurf** [comment]
@bagshik I would like to have any component that has a styled component in it have those styled components moved to their own file please

**Comment by bagshik** [comment]
Sure, should I move them in a particular folder or leave them where they are?

**Comment by EricTurf** [comment]
Probably in the same folder as the components so ex for `icon`

`icon.styled.js`

**Comment by bagshik** [comment]
#44 should do it, let me know if you need any changes 👌
