### ISSUE TITLE
Move theme to top level

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#56]
Currently theme is set in the `sudoku` game itself and not the whole app. Move the theme to the top level so all components have access to the theme

**Comment by bagshik** [comment]
Hey man, you're already working on this? 🤔

**Comment by EricTurf** [comment]
@bagshik I was about to but I am at work for the afternoon so I didn't start.

Feel free to take it tho :)

**Comment by bagshik** [comment]
@EricTurf 👌 so basically I need to move the `ThemeProvider` with all its logic to `app.jsx` and wrap it around `StyledApp`?
