### ISSUE TITLE
Add themes to sudoku game

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#8]
Currently the game is orange and the whole game is styled based on this object structure

```javascript
const orangeTheme = {
  primary: 'rgba(255,90,0,1)',
  secondary: 'rgba(0,0,0,1)',
  board: 'rgba(255,90,0,0.7)',
  overlay: 'rgba(255,90,0,0.2)'
};
```

Create any structure, give it a clever name and submit a screenshot with a pull request

**Comment by matiasjgoitea** [comment]
Hi i'm on it
