### ISSUE TITLE
[Feature] Add selection of `theme`

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#9]
Currently the sudoku game has the ability to use a theme but is passed a single object. This should be changed so that the user can change the theme from a select box.

Tasks:
- [ ] Move `orangeTheme` from `sudoku.jsx` to a new file which default exports an object keyed by theme name
- [ ] Create a simple single select component to reads in the keys of the `themes` object
- [ ] Pass down the theme object to `sudoku.jsx` so that the theme can be changed

**Comment by janczizikow** [comment]
Could I tackle this?

**Comment by EricTurf** [comment]
@janczizikow For sure have fun

**Comment by janczizikow** [comment]
Cool!

**Comment by matiasjgoitea** [comment]
Sorry, i didn't notice this issue. I solved it with #8 as well.

**Comment by EricTurf** [comment]
@janczizikow The ability to add a theme was added by @matiasjgoitea in #25 

I was wondering if you were able to change the dropdown select to a box with arrows like this:

<img width="239" alt="screen shot 2018-10-06 at 8 10 21 am" src="https://user-images.githubusercontent.com/29803403/46571236-5a4e3e80-c93f-11e8-9e68-13da00ddfa6e.png">

So clicking the arrows would cycle through the themes and change the board theme :)

Let me know
